In [ ]:
! mkdir ~/.kaggle

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
! cp drive/MyDrive/kaggle.json ~/.kaggle

In [ ]:
! kaggle datasets download pncnmnp/the-indian-movie-database

Dataset URL: https://www.kaggle.com/datasets/pncnmnp/the-indian-movie-database
License(s): other
Downloading the-indian-movie-database.zip to /content
  0% 0.00/4.09M [00:00<?, ?B/s]
100% 4.09M/4.09M [00:00<00:00, 199MB/s]

In [ ]:
! unzip /content/the-indian-movie-database.zip

Archive:  /content/the-indian-movie-database.zip
  inflating: 1950-1989/bollywood_1950-1989.csv
  inflating: 1950-1989/bollywood_meta_1950-1989.csv
  inflating: 1950-1989/bollywood_ratings_1950-1989.csv
  inflating: 1950-1989/bollywood_text_1950-1989.csv
  inflating: 1950-2019/bollywood_crew_1950-2019.csv
  inflating: 1950-2019/bollywood_crew_data_1950-2019.csv
  inflating: 1950-2019/bollywood_full_1950-2019.csv
  inflating: 1950-2019/bollywood_writers_data_1950-2019.csv
  inflating: 1990-2009/bollywood_1990-2009.csv
  inflating: 1990-2009/bollywood_meta_1990-2009.csv
  inflating: 1990-2009/bollywood_ratings_1990-2009.csv
  inflating: 1990-2009/bollywood_text_1990-2009.csv
  inflating: 2010-2019/bollywood_2010-2019.csv
  inflating: 2010-2019/bollywood_meta_2010-2019.csv
  inflating: 2010-2019/bollywood_ratings_2010-2019.csv
  inflating: 2010-2019/bollywood_text_2010-2019.csv
  inflating: collaborative/README.txt
  inflating: collaborative/genome_scores.csv
  inflating: collaborative/genome_tags.csv
  inflating: collaborative/links.csv
  inflating: collaborative/ratings.csv
  inflating: collaborative/tags.csv
  inflating: collaborative/titles.csv

In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
os.listdir('1950-2019')

['bollywood_crew_data_1950-2019.csv',
 'bollywood_crew_1950-2019.csv',
 'bollywood_writers_data_1950-2019.csv',
 'bollywood_full_1950-2019.csv']

In [ ]:
data1 = pd.read_csv('1950-2019/bollywood_full_1950-2019.csv')
data1.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112.0,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73.0,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549.0,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891.0,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280.0,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [ ]:
data2 = pd.read_csv('1950-2019/bollywood_crew_data_1950-2019.csv')
data2.head()

,crew_id,name,born_year,death_year,profession,known_for
0,nm0001408,Shekhar Kapur,1945,\N,actor|director|producer,tt0240510|tt0414055|tt0109206|tt0127536
1,nm0002172,Mukul Anand,1951,1997,director|writer|producer,tt0104607|tt0102201|tt0098999|tt0092026
2,nm0002411,Mani Kaul,1944,2011,director|writer|actor,tt0207626|tt0066514|tt0070009|tt0102515
3,nm0003939,Vikramaditya Motwane,1976,\N,producer|writer|director,tt0238936|tt3322420|tt1639426|tt1327035
4,nm0004072,Kaizad Gustad,1968,\N,director|writer|miscellaneous,tt0330082|tt3309662|tt0168529|tt0819646

In [ ]:
data3 = pd.read_csv('1950-2019/bollywood_crew_1950-2019.csv')
data3.head()

     imdb_id  directors                        writers
0  tt0042184  nm0025608            nm0025608|nm0324690
1  tt0042207  nm0490178            nm0161032|nm1879927
2  tt0042225  nm0707533                             \N
3  tt0042233  nm0788880            nm0592578|nm0788880
4  tt0042380  nm0439074  nm1278450|nm0438022|nm1301772

In [ ]:
data4 = pd.read_csv('1950-2019/bollywood_writers_data_1950-2019.csv')
data4.head()

,crew_id,name,born_year,death_year,profession,known_for
0,nm0000636,William Shakespeare,1564,1616,writer|soundtrack|miscellaneous,tt3894536|tt5377528|tt5932378|tt8632012
1,nm0002005,Agatha Christie,1890,1976,writer|camera_department,tt3402236|tt0029171|tt0051201|tt1349600
2,nm0002042,Charles Dickens,1812,1870,writer|soundtrack|miscellaneous,tt0096061|tt0063385|tt0095776|tt0119223
3,nm0002172,Mukul Anand,1951,1997,director|writer|producer,tt0104607|tt0102201|tt0098999|tt0092026
4,nm0002411,Mani Kaul,1944,2011,director|writer|actor,tt0207626|tt0066514|tt0070009|tt0102515

In [ ]:
data = data1.loc[:,['title_y','imdb_id','is_adult','year_of_release','genres','summary','actors']]
data.head()

,title_y,imdb_id,is_adult,year_of_release,genres,summary,actors
0,Uri: The Surgical Strike,tt8291224,0,2019,Action|Drama|War,Indian army special forces execute a covert op...,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,tt9472208,0,2019,War,The story of Battalion 609 revolves around a c...,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister,tt6986710,0,2019,Biography|Drama,Explores Manmohan Singh's tenure as the Prime ...,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,tt8108208,0,2019,Crime|Drama,The movie focuses on existing malpractices in ...,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,tt6028796,0,2018,Drama,Under the 'Evening Shadows' truth often plays...,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...

In [ ]:
data = data.merge(data3,on='imdb_id',how='left')

In [ ]:
data.head()

,title_y,imdb_id,is_adult,year_of_release,genres,summary,actors,directors,writers
0,Uri: The Surgical Strike,tt8291224,0,2019,Action|Drama|War,Indian army special forces execute a covert op...,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,nm2336554,nm2336554
1,Battalion 609,tt9472208,0,2019,War,The story of Battalion 609 revolves around a c...,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,nm10342614,nm2366632
2,The Accidental Prime Minister,tt6986710,0,2019,Biography|Drama,Explores Manmohan Singh's tenure as the Prime ...,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,nm9049092,nm9049093|nm10376880|nm9049092|nm4577451|nm103...
3,Why Cheat India,tt8108208,0,2019,Crime|Drama,The movie focuses on existing malpractices in ...,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,nm2265536,nm8006178
4,Evening Shadows,tt6028796,0,2018,Drama,Under the 'Evening Shadows' truth often plays...,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,nm1482161,nm1481242|nm1482161

In [ ]:
data.replace('\\N',np.nan,inplace=True)

In [ ]:
data.isnull().sum()

title_y              0
imdb_id              0
is_adult             0
year_of_release      2
genres               8
summary              1
actors              10
directors            8
writers            843
dtype: int64

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.isnull().sum()

title_y            0
imdb_id            0
is_adult           0
year_of_release    0
genres             0
summary            0
actors             0
directors          0
writers            0
dtype: int64

In [ ]:
data.duplicated().sum()

137

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.duplicated(subset=['title_y']).sum()

145

In [ ]:
data.drop_duplicates(subset=['title_y'],inplace=True)

In [ ]:
data['is_adult'].unique()

array([0])

In [ ]:
data.drop(columns=['is_adult'],inplace=True)

In [ ]:
data.head(3)

,title_y,imdb_id,year_of_release,genres,summary,actors,directors,writers
0,Uri: The Surgical Strike,tt8291224,2019,Action|Drama|War,Indian army special forces execute a covert op...,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,nm2336554,nm2336554
1,Battalion 609,tt9472208,2019,War,The story of Battalion 609 revolves around a c...,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,nm10342614,nm2366632
2,The Accidental Prime Minister,tt6986710,2019,Biography|Drama,Explores Manmohan Singh's tenure as the Prime ...,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,nm9049092,nm9049093|nm10376880|nm9049092|nm4577451|nm103...

In [ ]:
def classify_year(year):
  return year[2]*2

In [ ]:
data['year_of_release'].unique()

array(['2019', '2018', '2017', '2016', '2013', '2015', '2014', '1975',
       '2012', '2011', '2008', '2010', '2009', '2007', '2004', '2005',
       '2006', '1993', '1997', '2003', '1960', '2002', '2001', '2000',
       '1992', '1999', '1998', '1984', '1996', '1995', '1994', '1991',
       '1990', '1989', '1988', '1987', '1986', '1985', '1979', '1983',
       '1982', '1977', '1981', '1980', '1978', '1976', '1974', '1973',
       '1972', '1971', '1970', '1969', '1968', '1967', '1966', '1965',
       '1964', '1963', '1962', '1961', '1959', '1958', '1956', '1957',
       '1955', '1954', '1953', '1952', '1951', '1950'], dtype=object)

In [ ]:
data['year_of_release'] = data['year_of_release'].apply(classify_year)

In [ ]:
data['year_of_release'].unique()

array(['11', '77', '00', '99', '66', '88', '55'], dtype=object)

In [ ]:
data['genres'] = data['genres'].apply(lambda x : x.split('|'))

In [ ]:
data['summary'] = data['summary'].apply(lambda x : x.split(' '))

In [ ]:
data['actors'] = data['actors'].apply(lambda x : x.split('|'))

In [ ]:
data['directors'] = data['directors'].apply(lambda x : x.split('|'))

In [ ]:
data['writers'] = data['writers'].apply(lambda x : x.split('|'))

In [ ]:
data['year_of_release'] = data['year_of_release'].apply(lambda x : [x])

In [ ]:
data.head()

,title_y,imdb_id,year_of_release,genres,summary,actors,directors,writers
0,Uri: The Surgical Strike,tt8291224,[11],"[Action, Drama, War]","[Indian, army, special, forces, execute, a, co...","[Vicky Kaushal, Paresh Rawal, Mohit Raina, Yam...",[nm2336554],[nm2336554]
1,Battalion 609,tt9472208,[11],[War],"[The, story, of, Battalion, 609, revolves, aro...","[Vicky Ahuja, Shoaib Ibrahim, Shrikant Kamat, ...",[nm10342614],[nm2366632]
2,The Accidental Prime Minister,tt6986710,[11],"[Biography, Drama]","[Explores, Manmohan, Singh's, tenure, as, the,...","[Anupam Kher, Akshaye Khanna, Aahana Kumra, At...",[nm9049092],"[nm9049093, nm10376880, nm9049092, nm4577451, ..."
3,Why Cheat India,tt8108208,[11],"[Crime, Drama]","[The, movie, focuses, on, existing, malpractic...","[Emraan Hashmi, Shreya Dhanwanthary, Snighdade...",[nm2265536],[nm8006178]
4,Evening Shadows,tt6028796,[11],[Drama],"[Under, the, 'Evening, Shadows', , truth, ofte...","[Mona Ambegaonkar, Ananth Narayan Mahadevan, D...",[nm1482161],"[nm1481242, nm1482161]"

In [ ]:
data.set_index(np.array([i for i in range(data.shape[0])]),inplace=True)

In [ ]:
data['tags'] = (data['year_of_release']+data['genres']+data['summary']+data['actors']+data['directors']+data['writers'])

In [ ]:
data.head()

,title_y,imdb_id,year_of_release,genres,summary,actors,directors,writers,tags
0,Uri: The Surgical Strike,tt8291224,[11],"[Action, Drama, War]","[Indian, army, special, forces, execute, a, co...","[Vicky Kaushal, Paresh Rawal, Mohit Raina, Yam...",[nm2336554],[nm2336554],"[11, Action, Drama, War, Indian, army, special..."
1,Battalion 609,tt9472208,[11],[War],"[The, story, of, Battalion, 609, revolves, aro...","[Vicky Ahuja, Shoaib Ibrahim, Shrikant Kamat, ...",[nm10342614],[nm2366632],"[11, War, The, story, of, Battalion, 609, revo..."
2,The Accidental Prime Minister,tt6986710,[11],"[Biography, Drama]","[Explores, Manmohan, Singh's, tenure, as, the,...","[Anupam Kher, Akshaye Khanna, Aahana Kumra, At...",[nm9049092],"[nm9049093, nm10376880, nm9049092, nm4577451, ...","[11, Biography, Drama, Explores, Manmohan, Sin..."
3,Why Cheat India,tt8108208,[11],"[Crime, Drama]","[The, movie, focuses, on, existing, malpractic...","[Emraan Hashmi, Shreya Dhanwanthary, Snighdade...",[nm2265536],[nm8006178],"[11, Crime, Drama, The, movie, focuses, on, ex..."
4,Evening Shadows,tt6028796,[11],[Drama],"[Under, the, 'Evening, Shadows', , truth, ofte...","[Mona Ambegaonkar, Ananth Narayan Mahadevan, D...",[nm1482161],"[nm1481242, nm1482161]","[11, Drama, Under, the, 'Evening, Shadows', , ..."

In [ ]:
data = data.loc[:,['title_y','imdb_id','tags']]

In [ ]:
data['tags'] = data['tags'].apply(lambda x : [str(i).lower() for i in x if i!=''])

In [ ]:
data['tags'] = data['tags'].apply(lambda x : " ".join(x))

In [ ]:
data.head()

,title_y,imdb_id,tags
0,Uri: The Surgical Strike,tt8291224,11 action drama war indian army special forces...
1,Battalion 609,tt9472208,11 war the story of battalion 609 revolves aro...
2,The Accidental Prime Minister,tt6986710,11 biography drama explores manmohan singh's t...
3,Why Cheat India,tt8108208,11 crime drama the movie focuses on existing m...
4,Evening Shadows,tt6028796,11 drama under the 'evening shadows' truth oft...

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps = PorterStemmer()

In [ ]:
def stem(s):
  l=[]
  for i in s.split(' '):
    l.append(ps.stem(i))
  return " ".join(l)

In [ ]:
data['tags'] = data['tags'].apply(stem)

In [ ]:
data.head()

,title_y,imdb_id,tags
0,Uri: The Surgical Strike,tt8291224,11 action drama war indian armi special forc e...
1,Battalion 609,tt9472208,11 war the stori of battalion 609 revolv aroun...
2,The Accidental Prime Minister,tt6986710,11 biographi drama explor manmohan singh' tenu...
3,Why Cheat India,tt8108208,11 crime drama the movi focus on exist malprac...
4,Evening Shadows,tt6028796,11 drama under the 'even shadows' truth often ...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
movie_tags = cv.fit_transform(data['tags']).toarray()
movie_tags

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movie_similarity = cosine_similarity(movie_tags)

In [ ]:
movie_similarity.shape

(3286, 3286)

In [74]:
def get_recommendation(movie_name):
  movies=sorted(list(enumerate(movie_similarity[data[data['title_y']==movie_name].index[0]]))
    ,reverse=True,key=lambda x : x[1])
  indices=[]
  for i in range(1,6):
    indices.append(list(data.loc[movies[i][0],['title_y','imdb_id']]))
  return indices

In [75]:
get_recommendation('PK')

[['Carry On Munna Bhai', 'tt0456144'],
 ['3 Idiots', 'tt1187043'],
 ['Munna Bhai M.B.B.S.', 'tt0374887'],
 ['Sanju', 'tt6452574'],
 ['Yeh Teraa Ghar Yeh Meraa Ghar', 'tt0298606']]

In [64]:
import pickle

In [70]:
pickle.dump(data.to_dict(), open('data.pkl', 'wb'))

In [71]:
pickle.dump(movie_similarity, open('similarity.pkl', 'wb'))

In [72]:
sm = pickle.load(open('similarity.pkl','rb'))

In [73]:
sm

array([[1.        , 0.17083257, 0.04543109, ..., 0.02437575, 0.0280056 ,
        0.07418865],
       [0.17083257, 1.        , 0.0742156 , ..., 0.        , 0.        ,
        0.        ],
       [0.04543109, 0.0742156 , 1.        , ..., 0.05647825, 0.03244428,
        0.02148675],
       ...,
       [0.02437575, 0.        , 0.05647825, ..., 1.        , 0.06963106,
        0.06917145],
       [0.0280056 , 0.        , 0.03244428, ..., 0.06963106, 1.        ,
        0.05298129],
       [0.07418865, 0.        , 0.02148675, ..., 0.06917145, 0.05298129,
        1.        ]])

In [76]:
['asdf','sdfs']*2

['asdf', 'sdfs', 'asdf', 'sdfs']